export const healthLabels = [
  { id: "1", name: "alcohol-free" },
  { id: "2", name: "dairy-free" },
  { id: "3", name: "egg-free" },
  { id: "4", name: "fish-free" },
  { id: "5", name: "kidney-friendly" },
  { id: "6", name: "gluten-free" },
  { id: "7", name: "mustard-free" },
  { id: "8", name: "peanut-free" },
  { id: "9", name: "soy-free" },
  { id: "10", name: "low-potassium" },
  { id: "11", name: "No-oil-added" },
  { id: "12", name: "low-sugar" },
  { id: "13", name: "soy-free" },
  { id: "14", name: "vegan" },
  { id: "15", name: "vegetarian" },
  { id: "16", name: "wheat-free" },
  { id: "17", name: "tree-nut-free" },
];

export const categories = [
    { id: "1", name: "Alcohol-cocktail" },
    { id: "2", name: "Biscuits and cookies" },
    { id: "3", name: "Bread" },
    { id: "4", name: "Cereals" },
    { id: "5", name: "Condiments and sauces" },
    { id: "6", name: "Drinks" },
    { id: "7", name: "Egg" },
    { id: "8", name: "Main course" },
    { id: "9", name: "Omelet" },
    { id: "10", name: "Pancake" },
    { id: "11", name: "Preps" },
    { id: "12", name: "Preserve" },
    { id: "13", name: "Salad" },
    { id: "14", name: "Sandwiches" },
    { id: "15", name: "Soup" },
    { id: "16", name: "Starter" },
  ];
  
